spring:
  application:
    name: StoryCraft
  jackson:
    serialization:
      indent-output: true

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

api:
  jira:
    token: ${JIRA_API_TOKEN}
    url: https://jira.atlassian.net/rest/api/3
  openai:
    token: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
    model: "gpt-4"
